# Generated by Django 4.1.7 on 2023-02-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitinfo',
            name='SplitEntityId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
