# Generated by Django 4.1.7 on 2023-03-06 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_splitinfo_splitentityid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionResponse',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SplitBreakdown',
            fields=[
                ('SplitEntityId', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Amount', models.IntegerField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SplitBreakdown', to='app.transactionresponse')),
            ],
        ),
    ]
