# Generated by Django 4.1.7 on 2023-03-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transactionresponse_splitbreakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitbreakdown',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transactionresponse',
            name='Balance',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
